### ISSUE TITLE
[Feature Request] - Load Test with CSV input

### ISSUE THREAD

**Issue by sinclr4** [microsoft/azure-load-testing#1]
**Is your feature request related to a problem? Please describe.**
I need to be able to run a perf test with a CSV input. Although this is in the Test Configuration YAML, it's not clear how to do this. I receive an error 'File Path not allowed in Test Plan CSVDataSet Config'

**Describe the solution you'd like**
Could you provide an example with includes a CSV input to a test.

**Comment by kaumishra** [comment]
Hi @sinclr4 Thanks for trying out the service. You can use the CSV by referencing it as a file name instead of a fully qualified path in the JMX file and upload it along with the JMX script. Thanks for the feedback on the docs and sample. We are working to get those added.

**Comment by sinclr4** [comment]
Thank you!
