### ISSUE TITLE
[BUG] Test runs are failing to start

### ISSUE THREAD

**Issue by mmosallem** [microsoft/azure-load-testing#104]
**Describe the bug**
Multiple test runs are failing to start with generic error:
"There was an issue with the service. Please raise a ticket with support along with the run id of the test."

there's no other information that explains what's going on. This issue started happening yesterday.
 

**Expected behavior**
The test run should start normally,

**Screenshots**
![image](https://user-images.githubusercontent.com/13883021/190393581-4d19816b-b51d-48c8-bfec-bf1f67e6dddd.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser MS Edge
 - Version 105.0.1343.33 
 
**Additional context**

AB#1618133

**Comment by Nagarjuna-Vipparthi** [comment]
@mmosallem Can you please share the IDs of the test runs that failed?

**Comment by mmosallem** [comment]
/testRunId/a221f5ee-e9dd-4635-829c-882e64b37039/testId/a949d393-a09f-440f-bac9-e800db039c2c
/testRunId/3fb14673-212a-4869-883f-b7b669a0128b/testId/a949d393-a09f-440f-bac9-e800db039c2c
/testRunId/2ff3fb1b-e1f0-4a2a-9184-946dcc968037/testId/a949d393-a09f-440f-bac9-e800db039c2c
/testRunId/abf57c07-08a7-4f29-9b35-7ee572b93039/testId/7573689e-87d4-4217-910b-a0556d82e45c
/testRunId/34f23563-dc3f-4ddf-8348-7c9be54040fb/testId/7573689e-87d4-4217-910b-a0556d82e45c

**Comment by vinodramasubbu** [comment]
I am getting the below error when executing load tests
 "There was an issue with the service. Please raise a ticket with support along with the run id of the test.
![AzureLoadTestFailure](https://user-images.githubusercontent.com/79949043/195422847-1b654da4-faaa-460f-b2f6-0b4b29b8a547.png)

**Comment by vinodramasubbu** [comment]
I am also getting the below error when running load tests
"There was an issue with the service. Please raise a ticket with support along with the run id "
![AzureLoadTestFailure](https://user-images.githubusercontent.com/79949043/195423340-7e1b200c-bcf5-4512-a344-1db7cd04fb3a.png)
of the test.

**Comment by issacnitin** [comment]
@mmosallem  The jmx script refers to /root/artifacts/streams/1k.csv that is not avialable in VM. The CSV will be available in /root/artifacts folder. Please update your Jmx script

**Comment by Nagarjuna-Vipparthi** [comment]
> I am also getting the below error when running load tests "There was an issue with the service. Please raise a ticket with support along with the run id " ![AzureLoadTestFailure](https://user-images.githubusercontent.com/79949043/195423340-7e1b200c-bcf5-4512-a344-1db7cd04fb3a.png) of the test.

@vinodramasubbu Can you share the test run ID please for us to investigate?
