### ISSUE TITLE
[BUG] Can't configure private test traffic mode in the portal

### ISSUE THREAD

**Issue by jometzg** [microsoft/azure-load-testing#106]
**Describe the bug**
Private test traffic mode (AKA VNet integration) will not configure correctly in the portal.

**To Reproduce**
1. Using load test in East US and the target application VNet also in East US
2. After configuring a VNet subnet's NSG with the correct inbound and outbound rules
3. Choose "Private" for Configure test traffic mode under load
4. Select the VNet and Subnet
5. Press Apply

**Expected behavior**
The test should save correctly once the VNet and subnet are chosen.

**Screenshots**
![image](https://user-images.githubusercontent.com/56820659/192994445-9afedf39-a671-4437-bbd1-5113c74b3620.png)

**Desktop (please complete the following information):**
Windows 11

**Additional context**
I have tried this on a Microsoft AIRs subscription several times and also in an MSDN subscription
I have performed the tests as defined here https://learn.microsoft.com/en-us/azure/load-testing/how-to-test-private-endpoint#configure-your-load-test by enabling network watcher, creating a VM and running the 3 tests to (2 to BatchNodeManagement 29876 and 29877) and one to AzureLoadTestingInstanceManagement to 8080. All three of these pass correctly.

AB#1636042

**Comment by jometzg** [comment]
Having talked to John Stallo, it seems I need to explicitly add myself as "network contributor" to the subscription - it seems even if I am the global administrator.

**Comment by ninallam** [comment]
@jometzg We have mentioned this in our prerequisites. Please let us know if you are facing any issue. Closing this issue for now.
![image](https://user-images.githubusercontent.com/50437471/193522940-869d5eaf-645c-44a0-8c3e-86055124555d.png)
