### ISSUE TITLE
[BUG] Cannot create test with Load -> Private traffic mode

### ISSUE THREAD

**Issue by Eonasdan** [microsoft/azure-load-testing#111]
**Describe the bug**
We are attempting to follow [this article](https://techcommunity.microsoft.com/t5/apps-on-azure-blog/load-test-endpoints-with-access-restrictions-using-azure-load/ba-p/3610412). I've created a simple node web app (no code deployed), a load test resource, two vnets and a nat gateway with the public ip prefix deployed to East US. When I try to create a test loading a simple jmx file **without** the private traffic mode, it works correctly. If I create a new test exactly the same way except I set the traffic mode to private. After clicking create in the final step, the portal simply gives an error that it failed. There is no additional details or logs that I can find. 

**To Reproduce**
1. Follow the steps in the linked article
1. Receive error
![image](https://user-images.githubusercontent.com/1006516/197803589-678279d2-f8d7-4668-ba8b-b988f91767f8.png)

**Expected behavior**
No error 😄. We realize this is in preview but there's multiple articles that suggest this is a 'supported' feature.

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Chrome
 - Version 106

A coworker tried this on a mac. I'm not sure of his browser and version info.

AB#1656584

**Comment by Nagarjuna-Vipparthi** [comment]
@Eonasdan Can you please confirm if you are meeting all the prerequisites mentioned [here](https://learn.microsoft.com/en-us/azure/load-testing/how-to-test-private-endpoint#prerequisites)?

**Comment by Eonasdan** [comment]
We solved this by giving the load test resource a managed identity and giving that network contrib on the vnet. The docs should be updated to reflect this.

**Comment by Nagarjuna-Vipparthi** [comment]
@Eonasdan Great to know that it is working for you. There was an issue in our service, and it is fixed now. Can you drop the network contributor access to managed identity and check please? Thanks.

**Comment by Eonasdan** [comment]
@Nagarjuna-Vipparthi I disabled the managed identity on the load test resource and I was able to create a new test with a jmx file and run it successfully. Thanks
