### ISSUE TITLE
[BUG] Failing to create Tests using REST API - but can create Load Tests

### ISSUE THREAD

**Issue by patmci** [microsoft/azure-load-testing#120]
**Describe the bug**
I am using an Azure App Registration to create Azure Load Tests. I am able to create a Load Test and retrieve it. 
However when I attempt to create a test on that load test using the dataPlaneUri, I am denied access. 
My App has scopes for loadtests.read and loadtests.write.

**To Reproduce**
1. Create an Azure app registration
2. Add Apis for loadtests.read and loadtests.write
3. Authenticate from Postman and receive bearertoken
4. Create Load Test and receive dataplaneuri
5. Create Test using Patch instruction
6. Error

**Error message**
Bearer error="invalid_token", error_description="S2S17001: SAL was able to validate the protocol, but validation failed as none of the inbound policies were satisfied. Validation failures: '6ddb9c11-a689-43ec-b923-c673c49dea0c: InvalidAudience."

**Additional context**
My bearertoken will allow me to create the load tests, but not to create the tests on the load test.

AB#1680254

**Comment by Sachid26** [comment]
@patmci... does your app have the required roles? can you refer [this](https://learn.microsoft.com/en-us/azure/load-testing/how-to-assign-roles)

**Comment by Harshan01** [comment]
@patmci Can you try generating the access token with scope "https://cnt-prod.loadtesting.azure.com/.default"? I assume the token generated did not use any scope/audience

**Comment by patmci** [comment]
> @patmci... does your app have the required roles? can you refer [this](https://learn.microsoft.com/en-us/azure/load-testing/how-to-assign-roles)

Hi, thanks for this - I can confirm that the App has the contributor role on Load Test

**Comment by patmci** [comment]
> @patmci Can you try generating the access token with scope "https://cnt-prod.loadtesting.azure.com/.default"? I assume the token generated did not use any scope/audience

How would I add a scope like this in an Azure App Registration?

**Comment by ninallam** [comment]
@Harshan01 can you please help with this?

**Comment by patmci** [comment]
Thanks I got this working. I needed token with a resource of https://management.azure.com/ to create the load test.
As per @Harshan01 I was missing the scope https://cnt-prod.loadtesting.azure.com/.default for the PATCH operation.

So I ended up with 2 tokens, 1 with the resource in the header to get the dataplaneuri from LoadTest and one with the scope in the header using the dataplaneuri to create the test

**Comment by Satbir-B** [comment]
@patmci Thank you for your update. I wanted to ask, noticing the steps you took to reproduce this error

To Reproduce

Create an Azure app registration
Add Apis for loadtests.read and loadtests.write
Authenticate from Postman and receive bearertoken
Create Load Test and receive dataplaneuri
Create Test using Patch instruction
Error

Could you offer assistance on the second part? Adding Apis for loadtests.read and loadtests.write. When adding API permissions I am unable to find references to these at all. Were they added as scopes, under Expose Scopes App registration blade?

Thank you
