### ISSUE TITLE
[Feature Request] az CLI support for tests

### ISSUE THREAD

**Issue by DanielLarsenNZ** [microsoft/azure-load-testing#122]
**Is your feature request related to a problem? Please describe.**
I would like to be able to automate the running of load tests (without using a CD pipeline).

**Describe the solution you'd like**
az CLI commands to create and run Azure Load Service tests.

**Describe alternatives you've considered**
Could use a GitHub action for this, but I don't really need this in a pipeline at this stage.

AB#1686945

**Comment by tomkerkhove** [comment]
+1

**Comment by Nagarjuna-Vipparthi** [comment]
@DanielLarsenNZ Thank you for sharing your feedback. Az CLI support is on our roadmap. 
Meanwhile you can try REST API and SDKs for automation. You can find more details in the links below 
API: https://learn.microsoft.com/en-us/rest/api/loadtesting/

JavaScript: https://learn.microsoft.com/en-us/javascript/api/overview/azure/load-testing?view=azure-node-preview

Dotnet: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/loadtestservice?view=azure-dotnet-preview

Python: https://learn.microsoft.com/en-us/python/api/overview/azure/load-testing?view=azure-python-preview

Java: https://learn.microsoft.com/en-us/java/api/overview/azure/developer-loadtesting-readme?view=azure-java-preview

**Comment by DanielLarsenNZ** [comment]
Great! Thank you

**Comment by tomkerkhove** [comment]
Can we keep this issue open for Azure cli?

**Comment by tomkerkhove** [comment]
Any update on this?

**Comment by ninallam** [comment]
Azure Load Testing now supports creating tests from Az CLI https://learn.microsoft.com/cli/azure/load. Please try it out and let us know your feedback [here](https://aka.ms/malt-feedback).

**Comment by tomkerkhove** [comment]
Wonderful, thanks!
