### ISSUE TITLE
[Feature Request] Ability to run tests across multiple regions

### ISSUE THREAD

**Issue by DanielLarsenNZ** [microsoft/azure-load-testing#123]
**Is your feature request related to a problem? Please describe.**
I am testing web application firewall behaviour and would like to be able to send load test traffic from multiple regions/geos.

**Describe the solution you'd like**
The ability to schedule a test to run across multiple regions, each region with its own compute, but with the same test plan.

**Describe alternatives you've considered**
I could automate this using a GitHub action, but it would be tricky to coordinate. I could use az CLI to do this, if az CLI supported tests. See also #122 .

AB#1686946

**Comment by Nagarjuna-Vipparthi** [comment]
@DanielLarsenNZ Thank you for the feedback. This feature to generate load from multiple regions (geographically distributed load) is on our roadmap. 
Meanwhile, you can try running simultaneous tests from multiple regions. Az CLI support is on our roadmap. However, you can try automation using APIs and SDKs 

API: https://learn.microsoft.com/en-us/rest/api/loadtesting/

JavaScript: https://learn.microsoft.com/en-us/javascript/api/overview/azure/load-testing?view=azure-node-preview

Dotnet: https://learn.microsoft.com/en-us/dotnet/api/overview/azure/loadtestservice?view=azure-dotnet-preview

Python: https://learn.microsoft.com/en-us/python/api/overview/azure/load-testing?view=azure-python-preview

Java: https://learn.microsoft.com/en-us/java/api/overview/azure/developer-loadtesting-readme?view=azure-java-preview

**Comment by DanielLarsenNZ** [comment]
Thanks so much!
