### ISSUE TITLE
[BUG] Private Test wont provision

### ISSUE THREAD

**Issue by MarekLani** [microsoft/azure-load-testing#125]
**Describe the bug**
I have created private test deployed to freshly created vnet with subnet dedicated for ALT with sufficient IP Range (/24 mask running only one engine). It is deployed to North Europe. VNET/subnet has no outbound/inbound restrictions set, it is setup without NSG. (Tested also with "fully opened" NSG). To eliminate problem of internal endpoint not being reachable I configured my jmx file to target publicly accessible endpoint. Test won't get provisioned. Only error message I receive is following: "_There was an issue with the service. Retry again in sometime. In case the issue persists, raise a ticket with support._ "

**To Reproduce**
See above

**Expected behavior**
Test provisions and executes sucesfuly

**Screenshots**
N/A

AB#1687199

**Comment by Nagarjuna-Vipparthi** [comment]
@MarekLani Can you please share the test run ID for us to debug the issue? 
Also, when you tried with public endpoint, did you select the test traffic mode as 'Public'?

**Comment by MarekLani** [comment]
@Nagarjuna-Vipparthi  Thank you very much for your response! I tried running private test reaching private endpoint first that didn't work, so I tried publicly available endpoint as well and since my network is not restricting public outbound access, I was expecting it to work. Please can you instruct me where to find run id, since I can see only the name of the run.

**Comment by Nagarjuna-Vipparthi** [comment]
When you click on the test run and open the test results page, you will see a 'Share' option 

![image](https://user-images.githubusercontent.com/103505570/203977001-dee0a4a1-565f-4cc3-a9ae-0c6f344161aa.png)

**Comment by MarekLani** [comment]
I see, thank you here are the details:
/testId/65b0fa68-3f6e-40b2-b7a0-204b10b3b928/
testRunId/878da84f-26f3-45a8-ad37-4533e70b8068

**Comment by issacnitin** [comment]
@MarekLani From our internal diagnostics, we found that your subscription have Azure Policy restrictions which prevent deployment of public IP. Deployment of Public IP, NSG and Load Balancer is required for private load testing to work. We're working on surfacing this error to end customer. Please fix the policy restrictions to continue using the feature..

**Comment by MarekLani** [comment]
@issacnitin thank you very much for the explanation! Closing the issue now.

**Comment by gougakos** [comment]
> 

hi what is the status of this fix? we are trying to load test privately and get the issue for policy restrictions regarding the public ip. Lifting the restrisction is not an option due to security violation
