### ISSUE TITLE
The "updated on" does not change when a new run has been created for a Test

### ISSUE THREAD

**Issue by johnAgilisys** [microsoft/azure-load-testing#127]
**Describe the bug**
Run the test over mutiple cycles on different dates and the test "Update On" field shows the date of when the test was first created.

**Expected behavior**
The field shoud be updated to reflect the latest run for a test?

**Screenshots**
![image](https://user-images.githubusercontent.com/102304772/205277815-246e19ec-8d6f-4aba-851d-cecd0b43a513.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome]

AB#1692617

**Comment by Nagarjuna-Vipparthi** [comment]
@johnAgilisys The 'Updated on' field indicates the date on which any changes to the test configuration have been made. If the same test set up was run multiple times, it is not being considered as an update to the test configuration. 
For example, if you have added a pass/fail criterion, increased the number of test engines in an existing test, such changes are considered as updates to the test. 

If you are interested in knowing when the latest test run happened, you can look at the test run name, which includes the timestamp of the test run.

**Comment by johnAgilisys** [comment]
@Nagarjuna-Vipparthi  Thanks for the respone. Agree I am able to find the latest run from the name but that would mean drilling into each test to see the last run date and status. would have been useful to have that on the summary page of the tests
![image](https://user-images.githubusercontent.com/102304772/206184214-6b60095f-0378-4518-bd5c-16cd170968bd.png)

**Comment by Nagarjuna-Vipparthi** [comment]
@johnAgilisys thank you for the suggestion. We will add it to our backlog and explore ways of improving the interface for listing the test details.

**Comment by johnAgilisys** [comment]
thats great.. thanks.

**Comment by ninallam** [comment]
@johnAgilisys This enhancement has been added. Closing this issue for now. Please reopen if you have any issue.
