### ISSUE TITLE
[BUG] Unable to update engine instances for existing load tests

### ISSUE THREAD

**Issue by mithunshanbhag** [microsoft/azure-load-testing#130]
**Describe the bug**
If I attempt to update the 'engine instances' for any existing test, I hit the error: `Error occurred while updating [TEST NAME].`

**To Reproduce**
Please see gif below for exact repro steps.

![GIF 1-3-2023 4-59-59 PM](https://user-images.githubusercontent.com/2327905/210349827-9659e738-83f2-44d2-9bf3-e83496dc8ec0.gif)

**Some Details For Troubleshooting**
- Subscription ID: d0c33f09-f408-4bb7-935e-c53c50358a38
- Load Test Name: `Get_contoso-traders-cartsctprod.politebay-207fb230.eastus.azurecontainerapps.io` (reproes on any load test actually). 
- Load Test Region: East US

AB#1712044

**Comment by Sachid26** [comment]
@mithunshanbhag ... thank you for reporting this. I checked at my end but i couldn't reproduce the same. can you check once if this is still happening?

**Comment by mithunshanbhag** [comment]
@Sachid26: I've not been able to repro the issue since. Will close the issue for now (will re-activate it if I encounter this issue again).
