### ISSUE TITLE
[BUG] Unable to create a quick-test with a valid public endpoint

### ISSUE THREAD

**Issue by mithunshanbhag** [microsoft/azure-load-testing#135]
**Describe the bug**
I have a valid public API endpoint that I want to load-test against.  However, the load-test service throws an error when I attempt to create a quick test using that public endpoint. Please see attached recording.

**Screenshots / Recordings**
https://user-images.githubusercontent.com/2327905/212924531-18024a65-b44f-4620-a5c9-359902f76e99.mp4

**Additional Details**
1. API Endpoint: https://contoso-traders-cartsctprod.politebay-207fb230.eastus.azurecontainerapps.io/v1/ShoppingCart/loadtest
2. Azure Subscription ID: `d0c33f09-f408-4bb7-935e-c53c50358a38`
3. Resource group name: `contoso-traders-rg`
4. Region: `East US`
5. Load Test Resource Name: `contoso-traders-loadtestctprod`

Please let me know if any additional details are required.

AB#1720014

**Comment by Nagarjuna-Vipparthi** [comment]
@mithunshanbhag Thank you for reaching out. We are working on fixing this issue and will get back to you once it's fixed.

**Comment by radhikajain99** [comment]
@mithunshanbhag We have deployed the fix for the issue. Can you please check if it is working now?

**Comment by mithunshanbhag** [comment]
@radhikajain99, @Nagarjuna-Vipparthi: Thanks, verified as fixed now! Closing this issue now.
