### ISSUE TITLE
Test aborted after 4mins but carried on running for over 3 hours

### ISSUE THREAD

**Issue by Shaun-Regan** [microsoft/azure-load-testing#136]
Run ID c89b786d-c680-4238-904d-d07664243620

My test appears to have aborted in under 5 mins even though the test detail doesn't show any errors.  
The test summary in our pipeline shows the test carried on running for over three hours?

The error detail reads "There was an issue with the service. Please raise a ticket with support along with the run id of the test."

Please can you advise how this issue can be resolved and also have we been charged for over 6 hours of test execution (two instances of this test taking over 3 hours has happened twice since the 16th Jan)

Before the 16th Jan the test aborted after three mins but showed as completed, green, successfully step.

![screencapture-portal-azure-2023-01-18-15_49_39](https://user-images.githubusercontent.com/19474305/213220805-59547ac9-16b5-4e5a-979d-be0c89d019b1.png)

![Screenshot 2023-01-18 155057](https://user-images.githubusercontent.com/19474305/213220886-15c1b389-3206-4205-9264-c1463dc39670.jpg)

Thanks

AB#1726350

**Comment by Nagarjuna-Vipparthi** [comment]
@Shaun-Regan Thanks for reaching out. You shared the run ID of one of the occurrences. Can you please share the run ID of the other test run when this happened? 
We will look into this and get back to you.

**Comment by Shaun-Regan** [comment]
Hi 
Please find below the run ID of the other instances of our test runs that have the same issue.

9462e3ad-afc3-4db7-939b-cf384f19c528
d4fa0e0a-e1e6-4024-b531-eb1bd8593434

thanks

**Comment by Shaun-Regan** [comment]
Had another test run end of the day Friday, reported issue replicated. runID 5ae2c6db-546c-4de7-a785-f493f23a2292

**Comment by Vairime** [comment]
Hi, I have the same issue - test run takes so much time and finally I should cancel it manually.  I see error:
![image](https://user-images.githubusercontent.com/123447835/214240321-52a7e77a-bf4b-4133-834f-092dd04178f8.png)

All failed test run Ids that never stopped themselves:
3b7e34a2-ecef-4e01-b5aa-d7a53af00045
330d1563-dac5-4843-8060-ef536228304d
5819678f-a8cc-4035-b9c6-7a12909ac00a
c618e05b-9f0a-4081-9297-ffda0ec3504e
43cbe4f5-1e9e-4a73-965e-d4f3d9a280b4

**Comment by Shaun-Regan** [comment]
@Nagarjuna-Vipparthi Hi, is there any update on this issue?  Do you need anymore information from me to help with the investigation? Thanks

**Comment by ninallam** [comment]
@Shaun-Regan Since we are discussing this on #140, I'm closing this.
