### ISSUE TITLE
[BUG] Load test exhibits completely different load characteristics on 2nd run.

### ISSUE THREAD

**Issue by mithunshanbhag** [microsoft/azure-load-testing#141]
**Describe the bug**
1. I have a quick load test set up to use 5 virtual users, single-engine, duration = 120 seconds, ramp-up time = 120 seconds.
2. On first run, a total of 2521 requests are generated (average 21.9 requests/second).
3. On second run, a total of 10847 requests are generated (average 180.87 requests/second).
4. The second run seems to generate almost 8x the load. See the screenshot below.

**Details**

* Subscription ID: d0c33f09-f408-4bb7-935e-c53c50358a38
* Load Test Resource Name: `contoso-traders-loadtestctstg`
* Load Test Name: `contoso-traders-products`
* Run 1: `TestRun_2/3/2023_7:35:35AM`
* Run 2: `TestRun_2/3/2023_7:41:37AM`

**Screenshots**

* Runs 1 and 2 compared.
   ![image](https://user-images.githubusercontent.com/2327905/216561049-6b912fba-2e7e-41d1-8603-f820fe694d3c.png)

**Additional Details**

* For context, the second run is with chaos studio enabled (AKS chaos mesh with pod failures). But that does not explain why the load service is generating 8x the load.

CC: @MarcusFelling 

AB#1741010

**Comment by ninallam** [comment]
@mithunshanbhag As you can see, the load which is the Virtual Users is same. The number of requests depends on the response time of your application. The way VUs (or threads) work in JMeter is that once a thread sends a requests it waits till the response is received and then sends the next one. So if the response time is less, in the same duration the number of requests would be higher. Hope that answers your question.

**Comment by mithunshanbhag** [comment]
Thanks @ninallam, understood.

Closing this issue. Will follow up with Chaos Studio team separately on the other orthogonal issue (non responsive pods)
