### ISSUE TITLE
Scheduling Azure Load Testing from Azure Functions 

### ISSUE THREAD

**Issue by taruntomar-qa** [microsoft/azure-load-testing#142]
I can see Azure load test can be run manually from Azure UI.

I was looking if we can get some of the tests triggered/scheduled using Azure Functions.
Is it possible to schedule it, if Yes, then How?

Thank You

AB#1743146

**Comment by Nagarjuna-Vipparthi** [comment]
@taruntomar-qa Thanks for reaching out. We have REST APIs that can be used to schedule tests using Azure functions. We also have integration with Azure pipelines and GitHub actions if you are looking into integrate with your CI/CD pipelines. 

REST API - https://learn.microsoft.com/rest/api/loadtesting/ 
CI/CD integration - https://learn.microsoft.com/azure/load-testing/tutorial-identify-performance-regression-with-cicd

**Comment by taruntomar-qa** [comment]
@Nagarjuna-Vipparthi 

In the link you have mentioned, I did not see any option of how can I trigger an existing Performance Test that I had created manually in Azure Load Test.
REST API - https://learn.microsoft.com/rest/api/loadtesting/

Either has 'Create or Update Test' or 'Get  Test'. I don't see  an Http Request to Trigger/Run Test.

Please respond if I am missing something.

Thanks

**Comment by Nagarjuna-Vipparthi** [comment]
@taruntomar-qa These are the set of APIs to manage a test run - https://learn.microsoft.com/en-us/rest/api/loadtesting/dataplane(2022-11-01)/load-test-run 

Specifically, this API is to run an existing test - https://learn.microsoft.com/en-us/rest/api/loadtesting/dataplane(2022-11-01)/load-test-run/create-or-update-test-run?tabs=HTTP
