### ISSUE TITLE
[Feature Request]-Ability to update existing jmeter script

### ISSUE THREAD

**Issue by ShadowPic** [microsoft/azure-load-testing#2]
**Is your feature request related to a problem? Please describe.**
It is frustrating that I have to create a new test every time I have an update to an existing jmeter script.  I don't want to have to enter the pass/fail criteria and select the azure resource(s) be monitored over and over again.

**Describe the solution you'd like**
Ability to upload a replacement for the current jmeter script but retain all of the current options.

**Describe alternatives you've considered**
Ability to clone/copy an existing test and allow me to upload a new jmeter script but retain all other settings

**Additional context**

**Comment by ShadowPic** [comment]
sorry i just found out how to do this.

**Comment by johnsta** [comment]
No worries, @ShadowPic - thanks for raising the issue nonetheless, and glad you were able to figure it out. 

For others who are wondering how to do this:
1. In the Azure Portal, navigate to the test you wish to edit.
2. In the command bar, select **Configure**, then select **Test**.
![image](https://user-images.githubusercontent.com/12104064/144812424-2a3823ba-74c6-4331-b63a-c254cf608e5b.png)

3. In the **Test plan** tab, delete the existing jmx file and upload your new one.
![image](https://user-images.githubusercontent.com/12104064/144812598-898e6e90-9e3d-433d-811d-cbde3ec543db.png)

4. Don't forget to apply your changes!

We'll consider adding a how-to article to address this.
