### ISSUE TITLE
__GetSecret seems not to work

### ISSUE THREAD

**Issue by WouterSlob** [microsoft/azure-load-testing#25]
I've tried to use KeyVault icw Azure Load Testing, following the steps described at https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#secrets, but the __GetSecret seems not to be working.

What I did was:
- Enabled the system assigned managed identity for my Load Testing resource
- Create a KeyVault with a secret
- Added the SMI to the KeyVault Access Policies with all Secret Permissions
- At the test parameters configured a Secret with Name = ClientId and Secret = https://<my-keyvault>.vault.azure.net/secrets/ClientId/
- Added a User Defined Variables Config Element to my JMeter Test Plan and a variable with Name = ClientId and Value = 
${__GetSecret(ClientId)}
- In my request use ${ClientId}

After running my Test I found the string "${__GetSecret(ClientId)}" iso the secret in the log files of the webserver.

So it looks like __GetSecret did not work.

Searching the internet for "__GetSecret " also seem to return only the Azure Load Testing page.
Is there something special needed to get this working?

AB#1455476

**Comment by Sachid26** [comment]
Hi @WouterSlob .. thanks for reporting this and the detailed steps that you have done to enable authentication scenario. We are looking into this issue and will get back with some information soon.

**Comment by ninallam** [comment]
@kusweta Can you please check this?

**Comment by ninallam** [comment]
Hi @WouterSlob, we have fixed the issue with GetSecret. Could you please try running your test now and confirm if this is working for you?

**Comment by WouterSlob** [comment]
Hi @ninallam, do I have to recreate my Azure Load Testing resource?

Because at the moment tests are not running at all anymore.
I've already tried to create a new test without __GetSecret and that one stays in status "Executing", but no requests are send at all.
After cancelling the test status stays in "Cancelling", although I got a "Test run stopped." confirmation in the portal.
Also

**Comment by kusweta** [comment]
@issacnitin Can you please check this?

**Comment by WouterSlob** [comment]
@ninallam / @issacnitin : any update on this? Already tried re-creating the resource and that did not work. Also tests in another resource that used to work are not starting anymore.

**Comment by ninallam** [comment]
Hi @WouterSlob could you please check if you are still facing this issue?

**Comment by WouterSlob** [comment]
I've created #33 for the problems with execution. I'll try to test __GetSecret in a different way.

**Comment by WouterSlob** [comment]
__GetSecret works now. Thnx!
