### ISSUE TITLE
[Feature Request] CLI or ARM template provisioning

### ISSUE THREAD

**Issue by jometzg** [microsoft/azure-load-testing#29]
**Is your feature request related to a problem? Please describe.**
My customer wants to be able to automate the process of test creation and running so that a "standard set" of tests can be provisioned and run later.

**Describe the solution you'd like**
Test creation by an ARM template or through CLI calls.

**Describe alternatives you've considered**
I can see that there is a VS Code extension and also there are actions for pipelines. But the customer really wants to be able to deploy a library of tests and for others to later execute these. The execute element could be done in the portal, but I can't see how you can lodge a set of test scripts to be used later.

**Additional context**
This is in no sense a blocker for the customer, but it would be good to understand more on what automation is planned for load testing.

AB#1458968

**Comment by ninallam** [comment]
@jometzg Thanks for reaching out. CLI support is planned for Azure Load Testing. Currently we support ARM template for resource creation and Azure Pipelines / GitHub actions for test creation. If you are using any of these tools, we recommend you to commit your test scripts to your repo so that they are version controlled. These can be run from the pipeline when required. Does this help with the customer's scenario?

**Comment by dewolfs** [comment]
@ninallam Can you provide an example ARM resource template? When I create an Azure Load Test resource via the portal and try to export the template I get the message 

`"{
  "code": "ExportTemplateCompletedWithErrors",
  "message": "Export template operation completed with errors. Some resources were not exported. Please see details for more information.",
  "details": [
    {
      "code": "ResourceTypeSchemaNotFound",
      "target": "Microsoft.LoadTestService/loadtests",
      "message": "The schema of resource type 'Microsoft.LoadTestService/loadtests' is not available. Resources of this type will not be exported to the template."
    }
  ]
}`

When do you expect CLI support to be available?

**Comment by ninallam** [comment]
Hi @dewolfs you can get the ARM template from the repository https://github.com/Azure-Samples/nodejs-appsvc-cosmosdb-bottleneck/tree/main/ARMTemplate

**Comment by ninallam** [comment]
Azure Load Testing now supports creating tests from Az CLI https://learn.microsoft.com/cli/azure/load. Please try it out and let us know your feedback [here](https://aka.ms/malt-feedback).
