### ISSUE TITLE
[BUG] All result artifacts are not available in Azure pipeline after load test execution

### ISSUE THREAD

**Issue by agrawalamit31** [microsoft/azure-load-testing#40]
**Describe the bug**
All artifacts as part of results are not available after load test execution via Azure Pipeline.
There is only one csv file as part of results.
![image](https://user-images.githubusercontent.com/19320805/150812870-1a6746a2-d449-49e2-924c-a734488e1aa0.png)

**Expected behavior**
There is no index.html file and other required files as part of result.

AB#1465664

**Comment by agrawalamit31** [comment]
@ninallam FYI

**Comment by ninallam** [comment]
Hi @agrawalamit31 could you please check if the additional files were present when downloaded from the portal?
@kusweta can you please take a look at this?

**Comment by agrawalamit31** [comment]
@ninallam and @kusweta - I observed this behavior several times. Some time I got all files and some times only getting testreport.csv.

**Comment by ninallam** [comment]
@agrawalamit31 we have fixed this. Can you please confirm if this is working for you.

**Comment by agrawalamit31** [comment]
@ninallam  - I will verify and update you

**Comment by agrawalamit31** [comment]
@ninallam  - I verified it and it is working now and we are getting all artifacts under result folder via pipeline.
