### ISSUE TITLE
[BUG] jdbc connection

### ISSUE THREAD

**Issue by szymonlngr** [microsoft/azure-load-testing#5]
**Describe the bug**
Trying to call sql queries in SQL DB on VM (whitelisted IPs) but cannot 

**Error**
,java.sql.SQLException: Cannot load JDBC driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver',172.18.59.5

**Expected behavior**
on Desktop jmeter it works fine

**Additional context**
Do workers have jdbc driver? or there should be different syntax to connect to DB?

**Comment by johnsta** [comment]
Hi @szymonlngr, thank you for raising this scenario. The product team is looking at this issue and will respond with more information soon.

**Comment by kaumishra** [comment]
Hi @szymonlngr we currently do not support this scenario. However this is on our roadmap. I will update with a comment here once I have a timeline for it.

**Comment by Sachid26** [comment]
@szymonlngr . we currently support the scenario. You would need to upload your dependency JDBC JAR along with the JMeter script. Closing this for now, Please feel free to open the issue in case the issue persists.

**Comment by mcapped** [comment]
@Sachid26 I followed what you had suggested in uploading the JAR, but I'm getting the same error as the original poster. It works as expected in JMeter on my pc. Error: java.sql.SQLException: Cannot load JDBC driver class 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

![image](https://user-images.githubusercontent.com/25186277/210647599-ca413d59-c93e-4c81-a99b-33600b5de5e6.png)

**Comment by Sachid26** [comment]
@mcapped... have you configured the JDBC configuration into your JMeter test plan to connect to the sql server instance assuming you are connecting to sql server?
