### ISSUE TITLE
[BUG] Test Run was stuck in Executing state after adding Secret parameter

### ISSUE THREAD

**Issue by shilamontubig** [microsoft/azure-load-testing#61]
I've tried using KeyVault in Azure Load Testing, following the steps described at https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#secrets, but the test run was stuck in Executing Status. 

I have tried running a jmx file with no Secret parameter and it works fine with no issues. 

** Steps To Reproduce**

- Enabled the system assigned managed identity for my Load Testing resource
- Create a KeyVault with a secret
- Added the SMI to the KeyVault Access Policies with all Secret Permissions
- At the test parameters configured a Secret with Name = SUBSCRIPTIONKEY and Secret = https://.vault.azure.net/secrets/TestSubscriptionKey/
- Added a Global User Defined Variables Config Element to my JMeter Test Plan and a variable with Name = subscription_key and Value = ${__GetSecret(SUBSCRIPTIONKEY)}
- In my request I used ${subscription_key}

Actual Result: 
Test Run was stuck in Executing status
When it eventually failed no Test Logs were created. 
Cancelling the test run also took awhile. 

Other Details: 
Location: Australia East

AB#1495145

**Comment by ninallam** [comment]
Hi @shilamontubig can you confirm if you have provided the secret URI in the format https://myvault.vault.azure.net/secrets/mysecret/ ? Checking if you have intentionally removed the key vault name in the description above?

**Comment by shilamontubig** [comment]
Hi @ninallam Yes I have removed the vault name in the description above. The secret URI is in this format: https://myvaultname.vault.azure.net/secrets/TestWpsSubscriptionKey/.

**Comment by ninallam** [comment]
@shilamontubig Thanks for reporting the issue. There's seems to be some problem with the secret input parameter. As a workaround can you please try using a specific version of the secret for now? For example:
https://myvault.vault.azure.net/secrets/mysecret/ec96f02080254f109c51a1f14cdb1931. Please let us know if this is working for you.

**Comment by shilamontubig** [comment]
Hi @ninallam Thanks for your feedback. I have also tried the same format (https://myvault.vault.azure.net/secrets/TestSubscriptionKey/a9a15bc440134bea88b1f9dcd690a4) and I still got the same result. The test run was stuck in Executing state.

**Comment by ninallam** [comment]
@shilamontubig thanks for confirming. Could you share the test run ID to debug further? Testrun ID can be obtained from the Share URL in the test run. The last GUID is the test run ID.

![image](https://user-images.githubusercontent.com/50437471/157856629-bc9709ae-fd73-4baa-81c9-5526c5ab579e.png)

**Comment by ninallam** [comment]
@kusweta to debug this

**Comment by ninallam** [comment]
@shilamontubig is the test run working fine without secret parameters?

**Comment by shilamontubig** [comment]
hi @ninallam Yes, the test runs successfully without secret parameters. 
Here are the run ids that you can check: 
- cf16d5f5-9df6-4046-8501-a678a9d2a1ea 
- 42e3893a-c759-4c07-b69e-32ec1c2d524b

**Comment by ninallam** [comment]
Hi @shilamontubig We see that you are using secrets without defining user defined variables. Could you please use a user - defined variable as mentioned in the doc https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#use-secrets-in-apache-jmeter 
Please let us know if it works for you.
Meanwhile we will take this feedback to improve and make the necessary changes for secrets to work without user defined variables.

**Comment by shilamontubig** [comment]
Hi @ninallam. I have set-up the secret using a user defined variable based on the documentation previously but when it failed I reverted back to using environment variable function ie. ${__BeanShell( System.getenv("variableName") )}. 

Today, I tried using __GetSecret function again in the .jmx file and the run was still stuck in Executing state. Please see the User Defined variable below: 

 <elementProp name="subscription_key" elementType="Argument">
            <stringProp name="Argument.name">subscription_key</stringProp>
            <stringProp name="Argument.value">**${__GetSecret(TestWpsSubscriptionKey)}**</stringProp>
            <stringProp name="Argument.metadata">=</stringProp>
 </elementProp>

Run ID: **59059051-c972-4c54-b7cb-ebdc16b90021**

**Comment by cijuvargeeseNeu** [comment]
Hi @ninallam Any update on the above mentioned issue. I am also facing the same issue while including a secret in the jmx test. This appears to be working fine when I ran the test without ${__GetSecret()} function and passing the data as parameter 
Run ID: /testRunId/ac2f83e9-a525-4067-9024-633d5ef7602e

**Comment by ninallam** [comment]
@kusweta can you please check the above test runs?

**Comment by ninallam** [comment]
@shilamontubig @cijuvargeeseNeu we have fixed this issue. Could you please confirm if it is working for you now?

**Comment by cijuvargeeseNeu** [comment]
@ninallam I have checked this and it is working fine. Appreciate the help!!

**Comment by ninallam** [comment]
Thanks for confirming. Closing this issue.

**Comment by sreedharputtaguntaus** [comment]
@ninallam @kusweta I'm facing the same issue. Despite having the secret url as described in the documentation, I'm getting the Invalid Secret Url error in pipelines. Can either of you help me on this?
