### ISSUE TITLE
[BUG]Tests Fail and Test Result is "Not Applicable"

### ISSUE THREAD

**Issue by DiegoNoble** [microsoft/azure-load-testing#68]
Hello,

Some hours ago I started testing Azure load tests successfully, but then without changing anything the same tests started failing, the test result is "Not Applicable".

I tried creating new Azure Load test in many regions like East us, East us2, North Europe, but the error persists.

Is there a temporary service problem? 

AB#1513231

**Comment by Sachid26** [comment]
Hi @DiegoNoble ... Thank you for reporting the issue. Can you please help us with the below information:

- share the scenario that you are trying to test and the parameters like engine instances you are referring for each test. 
- Also, please share the screenshots of the error that you are seeing. 
- Test run id for the tests which failed and subscription id.

**Comment by Sachid26** [comment]
Hi @DiegoNoble ...Checking to see if you have had chance to provide this information. We will close this request post two days in case of no response. Please feel free to reach out to us in case you face the issue again.

**Comment by Sachid26** [comment]
Closing this as no response received. Please feel free to reach out in case you run into the issue again.
