### ISSUE TITLE
[BUG] Unable to create the Load Testing resource through the Portal. 

### ISSUE THREAD

**Issue by mkrconscius** [microsoft/azure-load-testing#7]
**Describe the bug**
Cannot create the resource from the Portal. It seems to be a resource name validation issue. 

**To Reproduce**
1. Go to https://portal.azure.com/#create/Microsoft.CloudNativeTesting
2. Fill in any resource name. I've tried all lower case, all upper, no numbers, only numbers etc. 
4. See error:
`Azure resource names cannot contain special characters \/""[]:|<>+=;,?*@&, whitespace, or begin with '_' or end with '.' or '-'.`

**Expected behavior**
Be able to create the resource. 

**Screenshots**
![image](https://user-images.githubusercontent.com/94358386/145024684-c5772166-ddc7-4331-a8a7-377dedcd34d1.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome 
 - Version 94

**Comment by felipe-allmeida** [comment]
I just faced this issue. It's kind of annoying haha.

@mkrconscius were u able to create trough the cli? Can you provide me the command if yes?

Thanks

**Comment by kaumishra** [comment]
@felipe-allmeida  @mkrconscius  Thanks for reporting this.We are checking this currently. Will update here once we have a fix.

**Comment by issacnitin** [comment]
@mkrconscius Microsoft product names are generally not allowed as resource names. So names such as visualstudio, windows are disallowed. I'm not sure if GitHub is disallowed as well, maybe the documentation is not updated. Will make sure to update the validation error message. Please create the resource with a different name

You can find the set of reserved words here: https://docs.microsoft.com/en-us/azure/azure-resource-manager/troubleshooting/error-reserved-resource-name

**Comment by krishna1s** [comment]
@felipe-allmeida @mkrconscius it should be working fine now (please do a page reload, if already opened ), feel free to reopen this ticket in case if it still doesn't work

**Comment by mkrconscius** [comment]
@krishna1s It works now, thanks!

**Comment by felipe-allmeida** [comment]
It is working! Thanks.
