### ISSUE TITLE
Add Azure Load Testing to KeyVault trusted services

### ISSUE THREAD

**Issue by s041507** [microsoft/azure-load-testing#70]
**Is your feature request related to a problem? Please describe.**
We have a KeyVault that is protected by a firewall. Therefore we cannot access it.

**Describe the solution you'd like**
Let Azure Load Testing be added as a trusted service for the KeyVault. I know it's not an Azure Load Testing issue, but please forward to the KeyVault team.

**Describe alternatives you've considered**
Wait for the Azure Load Testing VNet integration feature. Is there any news on when this becomes available? We also would like to test private APIs.

Also see: https://docs.microsoft.com/en-us/azure/key-vault/general/overview-vnet-service-endpoints#trusted-services
#

AB#1535674

**Comment by johnsta** [comment]
Hi @s041507, please reach out to me via email at john.stallo@microsoft.com regarding joining the private preview.
