### ISSUE TITLE
[BUG] Load Test Results initially have date of 12/31/1969

### ISSUE THREAD

**Issue by conradascott** [microsoft/azure-load-testing#72]
**Describe the bug**
The start time and end time for load test results are both 12/31/1969. The grids at the bottom have the message "The configured query window is requesting data outside of this metrics max retention period (93 days)..."

**To Reproduce**
1. Run a load test. 
2. View results
3. Look at Start Time and End Time at top of page.
4. Note that the dates are both 12/31/1969.

**Expected behavior**
The start and end date-times should correspond to the start and end of the test.

**Screenshots**
![image](https://user-images.githubusercontent.com/90776249/166835817-1e3edbfe-8656-484a-9f02-dde3e5ef8bfa.png)
![image](https://user-images.githubusercontent.com/90776249/166836049-972d57e7-0f99-423f-813c-5b151b5dfb55.png)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version: Version 101.0.1210.32 (Official build) (64-bit)

AB#1535516

**Comment by Sachid26** [comment]
Thank you for reporting this issue. We are investigating this and we will update once we learn something.

**Comment by krishna1s** [comment]
@conradascott Hi Conrad, This issue arises when a malformed URL is given in the JMX script and JMeter doesn't generate any load as the request URL is incorrect. You can see these errors in the output result CSV file with the 1969 timestamp. In this case, there won't be any load generated and you won't be able to see any metrics. We have added a fix where you will see the correct start and end time for execution instead of the 1969 timestamp. We are closing this bug with this fix. Please feel free to open if you need more help. Thanks.

**Comment by conradascott** [comment]
Hi @krishna1s, this is the URL that I used:

http://20.232.240.253/

It was embedded with the jmx file with this content. Can you please point out the malformed URL? Thanks!

<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.4.1">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="Test Plan" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <kg.apc.jmeter.threads.UltimateThreadGroup guiclass="kg.apc.jmeter.threads.UltimateThreadGroupGui" testclass="kg.apc.jmeter.threads.UltimateThreadGroup" testname="jp@gc - Ultimate Thread Group" enabled="true">
        <collectionProp name="ultimatethreadgroupdata">
          <collectionProp name="1400604752">
            <stringProp name="1567">5</stringProp>
            <stringProp name="0">0</stringProp>
            <stringProp name="48873">30</stringProp>
            <stringProp name="49710">60</stringProp>
            <stringProp name="10">10</stringProp>
          </collectionProp>
        </collectionProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
      </kg.apc.jmeter.threads.UltimateThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="homepage" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments"/>
          </elementProp>
          <stringProp name="HTTPSampler.domain">http://20.232.240.253/</stringProp>
          <stringProp name="HTTPSampler.port">80</stringProp>
          <stringProp name="HTTPSampler.protocol">http</stringProp>
          <stringProp name="HTTPSampler.contentEncoding"></stringProp>
          <stringProp name="HTTPSampler.path"></stringProp>
          <stringProp name="HTTPSampler.method">GET</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.implementation">HttpClient4</stringProp>
          <stringProp name="HTTPSampler.connect_timeout">60000</stringProp>
          <stringProp name="HTTPSampler.response_timeout">60000</stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>
