### ISSUE TITLE
[BUG] Azure load test with keyvault : error "Keystore file not found, loading empty keystore"

### ISSUE THREAD

**Issue by AL1055188** [microsoft/azure-load-testing#74]
I've tried using KeyVault in Azure Load Testing, following the steps described at https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#secrets, but the test run was stuck in Executing Status.

I have tried running a jmx file with no Secret parameter and it works fine with no issues.

** Steps To Reproduce**

Enabled the user assigned managed identity for my Load Testing resource
Create a KeyVault with a secret
Added the UMI to the KeyVault Access Policies with all Secret Permissions

I add on my https request a token = ${__GetSecret(......)}

Actual Result:
the error is "Keystore file not found, loading empty keystore"

**Comment by Sachid26** [comment]
Thank you for reporting this issue. We are looking into this and inform back once we have something.

**Comment by ninallam** [comment]
Hi @AL1055188 can you please share the test run ID for us to debug further? You can find that in the share URL in the Azure portal as shown below
![image](https://user-images.githubusercontent.com/50437471/167356521-6553c902-ce8c-4687-95a5-cb1c42438fff.png)

**Comment by AL1055188** [comment]
Hi @ninallam
I share with you the link of the test : [Link](https://portal.azure.com/#blade/Microsoft_Azure_CloudNativeTesting/NewReport/resourceId/%2Fsubscriptions%2F405626e2-249b-4c52-bc2c-3f5d76f8d29f%2Fresourcegroups%2Fazrg-iasd-loadtest%2Fproviders%2Fmicrosoft.loadtestservice%2Floadtests%2Fazure-load-test/testId/96409186-c6c8-4f81-98a2-e366839305b3/testRunId/decf3d16-df9f-4ab8-a200-2d38f6124068)
I don't want to use key store file.
I really want to implement this part : https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#akv_secrets

**Comment by ninallam** [comment]
@AL1055188 Thanks for this. Are you able to see test results in the dashboard? Is the test run still stuck in executing?

**Comment by AL1055188** [comment]
It is always the same error 401 unauthorized 
![image](https://user-images.githubusercontent.com/97894449/167392850-8c686188-cc97-45d0-aee7-930dfcb340a5.png)

**Comment by ninallam** [comment]
We will get back on this.

**Comment by ninallam** [comment]
@AL1055188 have you added the correct secret URL which configuring the load test?

**Comment by AL1055188** [comment]
I confirm : 
![image](https://user-images.githubusercontent.com/97894449/167395262-f29fe159-90a3-4864-b7fc-cbae8648d2ed.png)

**Comment by ninallam** [comment]
Hi @AL1055188 can you please confirm the above? Are you using Get Secret in the JMX as mentioned here https://docs.microsoft.com/en-us/azure/load-testing/how-to-parameterize-load-tests#jmeter_secrets

**Comment by AL1055188** [comment]
Yes I confim that I use GetSecret method.
We find a way.
When there was no oauth2, it works fine ! 
the problem came from oauth2 which had to configure the calls to retrieve the token and launch the test.
