### ISSUE TITLE
Rest Endpoint for Azure Load Test Service

### ISSUE THREAD

**Issue by VasanthMuniswamy** [microsoft/azure-load-testing#76]
Hi Guys,

Can you please help me with Rest Endpoints to fetch the data or resource from Azure Load Test Service. I have completed the load test and I want to automate the reports generation for that I need the endpoints. 

Kindly help me on this.

Thanks!

AB#1539098

**Comment by ninallam** [comment]
Hi @VasanthMuniswamy you can find APIs in GitHub public repo for here https://github.com/Azure/azure-rest-api-specs/tree/main/specification/loadtestservice. We are currently working on better documentation for the public APIs and will update you once it is piblished.

**Comment by VasanthMuniswamy** [comment]
Thanks @ninallam
