### ISSUE TITLE
[BUG]I followed the guideline to create a Azure load testing, but when I click create. always test is being created.

### ISSUE THREAD

**Issue by Ethan033100** [microsoft/azure-load-testing#78]
**Describe the bug**
I created a Azure load testing, after I uploaded Jmeter, and create. It showed nothing but always **Test is being created.**

**To Reproduce**
I followed the guideline: https://docs.microsoft.com/en-gb/azure/load-testing/quickstart-create-and-run-load-test

**Expected behavior**
It should bed move the resource page.

**Screenshots**
![image](https://user-images.githubusercontent.com/97595052/168781357-e7244b8d-c038-453d-804f-86b593827ee4.png)

Please someone help check on this situation.

**Comment by ninallam** [comment]
@Ethan033100 thanks for reaching out. Are you still facing an issue while creating the test?

**Comment by ninallam** [comment]
@Ethan033100 can you please confirm if this issue still exists?

**Comment by ninallam** [comment]
Closing this because of no response. @Ethan033100 please reopen if it is still not working.
