### ISSUE TITLE
Support for Azure Monitor Custom Metrics?

### ISSUE THREAD

**Issue by jimcomiskey** [microsoft/azure-load-testing#79]
We have implemented some custom metrics to help understand our load, such as Operation Count.  When doing manual load testing, we can watch this custom metric and see how busy the server becomes when submitting larger requests.

When adding metrics to my Azure Load Test, I can see the "out of the box" metrics for my Application Insights instance.  But, the custom metrics are not available.  Would like to be able to select Custom Metrics and display them like this in the Load Testing Components.

![image](https://user-images.githubusercontent.com/6228438/168850787-f0d8d0d8-1b0f-454d-b99d-cc66284e87e2.png)

**Comment by ninallam** [comment]
Hi @jimcomiskey you should be able to view custom metrics as well in the test run dashboard. Once you add the App insights resource to your App components, you can configure the metrics you want to see as shown below.
![image](https://user-images.githubusercontent.com/50437471/169228473-4a5151db-ddc5-40ba-95aa-74239b8e1e94.png). Please let us know if this works for you.

**Comment by jimcomiskey** [comment]
Hi @ninallam , I can add App Insights to my Test, but when I go to select Metrics, I only see metrics found under Application Insights Standard Metrics.  I cannot access Custom Metrics which I have developed for tracking the system load.  

These are available in Azure Load Testing:

![image](https://user-images.githubusercontent.com/6228438/169353208-6cc0a940-f822-4e50-95a4-f50123c93e9f.png)

These custom metrics are not:

![image](https://user-images.githubusercontent.com/6228438/169352919-3e22e185-7247-4b18-84fc-b63991b82adb.png)

![image](https://user-images.githubusercontent.com/6228438/169353346-24d24866-1250-42c1-ba49-819164632571.png)

**Comment by krishna1s** [comment]
Hi @jimcomiskey can you share the screenshot of Configure metrics screen, are you able to see your custom metrics namespace in the Metric Namespace dropdown?

**Comment by ninallam** [comment]
@jimcomiskey can you please confirm the above?

**Comment by ninallam** [comment]
Closing this because of no response. @jimcomiskey please reopen if you are still facing this issue.
