### ISSUE TITLE
[BUG] Real pricing vs in docs

### ISSUE THREAD

**Issue by szymonlngr** [microsoft/azure-load-testing#8]
I have created this resource for one day and ececuted one test (that would not last longer than few minutes. What I see in billing for it shows as:
![image](https://user-images.githubusercontent.com/61535281/145024566-b7c4f3a3-54bb-4bc7-97d6-3966f1300b33.png)

While in pricing it shows $10 per month:
https://azure.microsoft.com/en-us/pricing/details/load-testing/
![image](https://user-images.githubusercontent.com/61535281/145024764-81de1794-83ca-43e6-a61b-a058a7c89e24.png)
Is that bug or I have been billed upfront for whole month? (I got billed for this one day 7.68euro (I have deleted resource to avoid additional costs just in case)

**Comment by johnsta** [comment]
Hi @szymonlngr, sorry for the delay as we looked into this to confirm accuracy. What you are seeing is intended. The $10 charge (per load test resource) is emitted at the time the resource is created and is valid for the remainder of the month. Following that, the $10 charge will be emitted again on the first of the each month that the resource exists.

**Comment by szymonlngr** [comment]
@johnsta I have removed my resource after few days, but after 1 month i got billed again. This certainly should not happen so I would say that it is some kind of Bug
