### ISSUE TITLE
[Feature Request] Support System Properties

### ISSUE THREAD

**Issue by MonikaReddy-MSFT** [microsoft/azure-load-testing#82]
Is there a planned update to support this? I was previously using OctoPerf to test an MTLS-secured service and it was working fine, uploading and specifying a keystore (PFX) through system properties. It feels like this is a pretty obvious use case, and I would love to leverage azure's load test instead.

**Comment by ninallam** [comment]
Hi @MonikaReddy-MSFT thanks for reaching out. This feature is on our roadmap and we'll let you know once it is available.
cc: @Nagarjuna-Vipparthi

**Comment by ninallam** [comment]
Hi @MonikaReddy-MSFT Azure Load Testing now supports client certificates. Please checkout this documentation https://learn.microsoft.com/en-us/azure/load-testing/how-to-test-secured-endpoints?tabs=portal#authenticate-with-client-certificates.
I'm closing this feature request. If you face any issues, please raise a new issue of the type bug.
