### ISSUE TITLE
Support for Azure Monitor Custom Metrics?

### ISSUE THREAD

**Issue by jimcomiskey** [microsoft/azure-load-testing#84]
**Unable to re-open my previous issue, so I am submitting again with more information requested.**

We have implemented some custom metrics to help understand our load, such as Operation Count. When doing manual load testing, we can watch this custom metric and see how busy the server becomes when submitting larger requests.

When adding metrics to my Azure Load Test, I can see the "out of the box" metrics for my Application Insights instance. But, the custom metrics are not available. Would like to be able to select Custom Metrics and display them like this in the Load Testing Components.

![image](https://user-images.githubusercontent.com/6228438/172907402-40bb3393-47f3-4ee0-b215-033b66a2bcbb.png)

I can add App Insights to my Test, but when I go to select Metrics, I only see metrics found under Application Insights Standard Metrics. I cannot access Custom Metrics which I have developed for tracking the system load.

These are available in Azure Load Testing:

https://user-images.githubusercontent.com/6228438/169353208-6cc0a940-f822-4e50-95a4-f50123c93e9f.png

These custom metrics are not:

![image](https://user-images.githubusercontent.com/6228438/172908727-2d5cfad3-150a-4a22-9eb9-ad647dbbbe0b.png)

![image](https://user-images.githubusercontent.com/6228438/172908760-60308f09-5b39-43b3-a434-4fc4de38543a.png)

AB#1552956

**Comment by jimcomiskey** [comment]
To respond to the question in the previously closed Issue:

> Hi @jimcomiskey can you share the screenshot of Configure metrics screen, are you able to see your custom metrics namespace in the Metric Namespace dropdown?

![image](https://user-images.githubusercontent.com/6228438/172909545-0d7a68a3-4ddc-4f6f-9157-ba874ef195b1.png)
I am able to see azure.applicationinsights namespace.  That seems to be where my custom metrics reside.  I can see them in Application Insights, but I cannot see them when using the Configure Metrics screen.  

These metrics fall under "Log based Metrics", rather than "Application Insights standard metrics".  Is that why I can't use them with Azure Load Testing Configure Metrics?

**Comment by ninallam** [comment]
@krishna1s can you please take a look at this?

**Comment by ninallam** [comment]
Hi @jimcomiskey can you please send an email to azloadfeedback@microsoft.com so that we can set up some time with you to debug this?

**Comment by radhikajain99** [comment]
@jimcomiskey @ninallam This issue has been fixed now. Please let us in case of any issues.
