### ISSUE TITLE
[BUG] Pipeline with yaml config with secret uris does not work

### ISSUE THREAD

**Issue by nilsgaeq** [microsoft/azure-load-testing#86]
**Describe the bug**
Using `AzureLoadTest@1` task in azure devops, setting up yaml configuration as described in https://docs.microsoft.com/en-us/azure/load-testing/reference-test-config-yaml, the task fails with `##[error]Invalid secret url`. Setting up the same config in azure portal, and downloading the input file, yields exact same configuration

**To Reproduce**
1. Set up pipeline with `AzureLoadTest@1`
2. Reference a test configuration yaml as described in https://docs.microsoft.com/en-us/azure/load-testing/reference-test-config-yaml
3. Make sure the keyvault identity has access to the keyvault
4. Run pipeline
5. Pipeline fails

**Expected behavior**
Pipeline should not fail

**Additional context**
Output yields that AzureLoadTest task v1.2.2 is being used

AB#1554859

**Comment by abranj1219** [comment]
Thanks for reporting this. We will check this and get back to you!!

**Comment by sreedharputtaguntaus** [comment]
I have the same issue. Followed the steps exactly as described in the documentation and also the Load Test Resource has access to the key vault secrets but it is failing in the pipeline saying, "Invalid Secret Url"

**Comment by ninallam** [comment]
@nilsgaeq @sreedharputtaguntaus We have fixed this issue. Can you please confirm if it is working now?

**Comment by ninallam** [comment]
@nilsgaeq @sreedharputtaguntaus Can you please confirm if it is working now?

**Comment by ninallam** [comment]
Closing this since we haven't received any response. Please re-open if you are still facing this.
