### ISSUE TITLE
AccessLogSampler can't find Log File

### ISSUE THREAD

**Issue by camandrewz** [microsoft/azure-load-testing#87]
I am attempting to use JMeter's AccessLogSampler plugin, but I am running into issues with finding my log file. I have uploaded both the test script as well as the log file, and I am only specifying the filename without the path. Is there something I'm missing?

AB#1557751

**Comment by Sachid26** [comment]
Thank you for reporting this issue. We will look and get back on this.

**Comment by Sachid26** [comment]
Closing this issue as we haven't received any response. please reach out in case you run into this issue again.
