### ISSUE TITLE
Pipeline runs successfully but does not publish results (pipeline) or create a test run in Azure Load Testing

### ISSUE THREAD

**Issue by johnAgilisys** [microsoft/azure-load-testing#90]
**Describe the bug**
The test results are not published in the CI/CD pipeline. Secondly a test run is also not generated in Azure Load Testing

**To Reproduce**
1. Run the pipeline 
2. Step execute successfully and runs the load test
3. Test reults arent published to the CI/CD Pipeline
4. Test Run is not generated in the Azure Load Testing (Azure Portal)

Alternatively
1. Go to Azure portal and open the Azure Load Testing service
2. Create a Test plan and upload the Jmeter file
3. run the Test 
4. No test run is generated in the test plan

**Expected behavior**
I should atleast see a test run generate in the Azure Portal

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]Windows 10
 - Browser [chrome]

Previous Successful Run
![image](https://user-images.githubusercontent.com/102304772/177775872-747ddba1-8122-4ef5-bd49-2118b2d441ef.png)

Current Failed result
![image](https://user-images.githubusercontent.com/102304772/177775576-f0b28f7c-27ff-47a4-b355-78628e1ce6dd.png)

AB#1567518

**Comment by LisaKemeling** [comment]
I had this issue yesterday as well. 
Also tried a new test and it got stuck while provisioning and failed after about 10 minutes. At some point I got it to run successfully but when trying a new run it succeeded but did not actually run in the portal.
Also existing tests that used to run successfully, failed or succeeded in the pipeline but did not actually run.

**Comment by johnAgilisys** [comment]
The pipeline is generating results for the test run. What was the issue as I havent changed anything for it to work

**Comment by ninallam** [comment]
@johnAgilisys @LisaKemeling thanks for reaching out. There were some issues with provisioning in the service during this time. That could be the reason for failure. Can you share the test id so that we can investigate this further? This can be found in the browser URL when you navigate to the test.

**Comment by johnAgilisys** [comment]
@ninallam -The issue is resolved now and is working as expected.. As you can see in the screenshot it did not provision anything and no test run was created in Azure Load testing

![image](https://user-images.githubusercontent.com/102304772/177964122-72d1354f-4900-44b9-aa2e-2192e2bbb601.png)

**Comment by LisaKemeling** [comment]
The issue @johnAgilisys mentions seems to be something else indeed, I had that also yesterday. I just ran one of the tests again and now it works fine.

**Comment by ninallam** [comment]
@radhikajain99 can you please check why does the pipelines task report success even when the test run is not created?

**Comment by radhikajain99** [comment]
@ninallam We were not failing the pipeline task in case of validation timeout. The fix for this has been deployed
