### ISSUE TITLE
Validation failed: Timeout validating the JMX script. Please try uploading the JMX script again.

### ISSUE THREAD

**Issue by mmosallem** [microsoft/azure-load-testing#97]
getting this error when trying to create a test. 

**Validation failed
Timeout validating the JMX script. Please try uploading the JMX script again.**

the test is created despite that, but when i try to run test i get another error:

**Failed
Timeout starting the test. Please try running the test again.**

the test runs locally just fine. 
attached the jmx file.
[ocs-int-test.zip](https://github.com/microsoft/azure-load-testing/files/9375001/ocs-int-test.zip)

AB#1594575

**Comment by mmosallem** [comment]
quick update on this, I had the user defined variables in the test plan element itself as show below
![image](https://user-images.githubusercontent.com/13883021/185687023-38d995e7-96e5-4d81-8bb5-400b9cf5b9cc.png)
 

Now after removing those variables and adding a new User Defined Variables element with the same variables there, every thing worked just fine!

![image](https://user-images.githubusercontent.com/13883021/185686907-a9f257c7-82e2-4630-a249-2c8462862f0a.png)

**Comment by Sachid26** [comment]
@mmosallem ..  We see that your issue got resolved. can we close this thread?

**Comment by mmosallem** [comment]
@Sachid26 Yes.
